on:
  push:
    branches:
    - master
    - 'release/**'
    - 'cicd/**'
    - dev
  pull_request:
    branches:
    - master
    - 'release/**'
    - 'cicd/**'
    - dev

# TODO: change jobs to work with matrix
# TODO: create a custom container to run these jobs in: https://docs.github.com/en/actions/using-jobs/running-jobs-in-a-container
# TODO: find a way to make `runs-on` common for all jobs

# See how to run with containers in Github Actions: https://docs.github.com/en/actions/using-jobs/running-jobs-in-a-container
jobs:
  backboi:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backboi
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Test codebase
        run: go test -v ./...
      - name: Check codebase builds successfully
        run: go build -v ./...
  frontboi:
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: frontboi
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run test